name: InlineSuggest
author: jplarson
category: Interface
tags: [auto suggest, suggest]
docs: http://github.com/jplarson/InlineSuggest/blob/master/README.md
demo: http://www.jpl-consulting.com/projects/MooTools/InlineSuggest/Demo/